### ISSUE TITLE
MongoUserStore should have a static factory method instead of ctor

### ISSUE THREAD

**Issue by tugberkugurlu** [tugberkugurlu/AspNetCore.Identity.MongoDB#35]
`MongoUserStore` ctor potentially performs an expensive I/O operation. Because of this, we should expose a factory method rather than making this part of the ctor.

**Comment by zokkan** [comment]
Hi @tugberkugurlu , will you continue to work on issues?

Thank you.

**Comment by tugberkugurlu** [comment]
Hi @zokkan! Yes, I was inactive on this but started finishing up a few things now to target ASP.NET Core Identity v2. Let me know if you want to help out!

**Comment by zokkan** [comment]
Hi @tugberkugurlu, I'm getting familiar so I won't be able to help, I'm looking a solution to help me instead. If I feel that I can help someday, I will inform you, promise. 😄

**Comment by tugberkugurlu** [comment]
Cool, this will help you. Use it 🙂

**Comment by dealproc** [comment]
I'm implementing this at this time, but the issue is the registration seems to still need to use `.GetAwaiter().GetResult()` at this point.  I would be interested in either 1) use a `TaskHelpers.RunSync(await () => )` method, or if @tugberkugurlu has a suggestion on how we can setup the Services collection to run async as the example to indeed run the method async as part of the singleton registration.  Check-in on this will be happening momentarily.
